version: '3'
services:

  redis:
    image: 'redis:alpine'
    container_name: pr-redis

  postgres:
    build:
      context: .
      dockerfile: DockerfilePostgres
    container_name: pr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  prnode:
    depends_on:
      - postgres
      - redis
    container_name: pr-node
    build: .
    environment:
      NODE_ENV: production!
    ports:
      - '8888:8888'
    links:
      - postgres
      - redis
